### ISSUE TITLE
WiFiEventHandler not a type???

### ISSUE THREAD

**Issue by dumais92** [gmag11/FSBrowserNG#1]
hi, 
I was trying to compile the sketch and received this error 

\libraries\FSBrowserNG-master/FSWebServerLib.h:84:5: error: 'WiFiEventHandler' does not name a type

     WiFiEventHandler onStationModeConnectedHandler, onStationModeDisconnectedHandler;

How can I resolve this issue?

Thanks.

**Comment by gmag11** [comment]
Hi. You probably need to update esp8266 libraries.

**Comment by dumais92** [comment]
Now I have this error. What did I do wrong?
\ESPAsyncWebServer-master\src\WebHandlers.cpp:67:64: error: 'strftime' was not declared in this scope

   strftime (result,30,"%a, %d %b %Y %H:%M:%S %Z", last_modified);

**Comment by gmag11** [comment]
I saw that error before. It solved when I installed esp8266 library using GIT source like stated on https://github.com/esp8266/Arduino#using-git-version

**Comment by gmag11** [comment]
Arduino boards manager installs it in a different place and it may produce errors like that

**Comment by dumais92** [comment]
Thanks it worked! :)

**Comment by dumais92** [comment]
Now i'm able to program spiffs and arduino ide programme fsbrowserNG but where do I change the config.json file to connect to my router? Sorry for my english i'm french.

**Comment by gmag11** [comment]
When it's not configured, it starts as an open access point. So you can connect to it and open 192.168.1.4/admin

**Comment by dumais92** [comment]
Hi, that's great! I'm able to see the index.htm. Can you give me a link were I can read and understand the code of index.htm? The purpose of my project is to send information to the esp8266 from the web.
thanks again!

**Comment by gmag11** [comment]
index.htm is got from [original FSBrowser example](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WebServer/examples/FSBrowser) where I got inspired to start with this project. I do not know where they got the code, and Javascript is minimized so it is difficult to analyze.

There are plenty of tutorials and examples on how to add graph visualizations over the Internet. For instance have a look to http://www.chartjs.org/ or https://www.sitepoint.com/15-best-javascript-charting-libraries/

You can use microAJAX like included index.html, WebSockets or Events to send values.

**Comment by gmag11** [comment]
I close this issue. You can reopen if you think it is necessary.
