### ISSUE TITLE
debug output problem.

### ISSUE THREAD

**Issue by mickey50** [gmag11/FSBrowserNG#11]
When I comment the RELEASE define to enable debug output ,I find an error 
no matching function for call to 'HardwareSerial::printf(const String&)'
how can I make this work ? thx.

**Comment by minida28** [comment]
Hi I found a workaround, try change line 836 in .cpp file

from
```arduino
DEBUGLOG(request->url());
```
into
```arduino
DBG_OUTPUT_PORT.println(request->url());
```

**Comment by mickey50** [comment]
@minida28 
thx, I think the line change into 
`DEBUGLOG(request->url().c_str());`
may be better

**Comment by minida28** [comment]
@mickey50 
oops. wrong comment. I will try out your workaround.

**Comment by minida28** [comment]
@mickey50 
Tested that and works great. Thank you.

**Comment by gmag11** [comment]
Exactly @mickey50 . Thank you. It is already fixed on master branch.
