### ISSUE TITLE
intermittent wiFi connection issues 

### ISSUE THREAD

**Issue by species5618** [gmag11/FSBrowserNG#14]
I was having a less then 1 in 4 WiFi connection success , from either cold boot, warm reset or upload

in my fork (not yet commited) i have changed to (which seem to fix the issue)

void AsyncFSWebServer::configureWifi() { 
     **WiFi.disconnect();**
     WiFi.mode(WIFI_STA); 
     //currentWifiStatus = WIFI_STA_DISCONNECTED;

**Comment by gmag11** [comment]
May you confirm that fixes your problem?
Is that the only change that you've made? If so, please make a pull request.

**Comment by species5618** [comment]
Yes my project is now connecting 100% reliably
but currently includes a few extra pages, once I have finished, I will re test on a clean copy of FSBrowserNG
and arrange a pull request
