### ISSUE TITLE
Not an issue, just a request

### ISSUE THREAD

**Issue by Saaif88** [gmag11/FSBrowserNG#15]
Hello gmag11,

First off, this is a fantastic project, it works beautifully when it comes to serving HTML files and it is very fast. Secondly, I'm relatively new to this and I don't know where else to ask this question so I'll put it here:

Can you maybe add some functionality to the main page along with some explanations? It's nice to read the status of the analog input and the GPIO pins, but do you think that you can have a write example in there somewhere as well? 

This is a really complex project for a beginner like me, and it would really help a lot if you could add some more examples and support. Right now I can't even find the code you are using to read the status of the GPIO pins, and if you could add a simple button to turn on and off one of the pins, along with an explanation of how you did so, that would help a lot of people I'm sure!

Thanks! (Feel free to move this to wherever it needs to go)

**Comment by species5618** [comment]
hi Saaif88, 
not wanting to detract from the outstanding work of Gmag11, but have a look at my fork from this project
https://github.com/species5618/FSBrowserNG
it no where near complete and does need a good tidy up, but has the following extras 

using MQTT, https://en.wikipedia.org/wiki/MQTT
I have remote control, and emote reading of GPIO and sensors 
I use it on a wemos d1 mini, and have a PCB with relays etc on it !describe on the Docs Section

 Pin map defined in global.h
* Basic i/o via MQTT working, and supporting retained messages so restart in to correct output state
* DHT11 and DHT22 supoprted, support for dallas temperature sensor (untested)
* Analog in working
* MQTT "will" TOPIC used to signal device lost contact, up/down
* MQTT root topic supported, i used this for bridging segregation
* Additional Web pages working for 
  * MQTT settings
  * Pin i/o mode
* MQTT update interval control , so update rate can be limited , usefull when on freeplan from cloudmqtt
* Frequency in pins
  * Frequency, double edge, double edge will be Hz * 2
  * Support resetable big int Totaliser 
* PWM out Pins
* optional on timeout for outputs, so relays will shut down after timeout, set default time out in WEB ui, or override with : on MQTT messages 1:30 will turn on for 30 seconds then off

 
ToDo
 REST API
 2FA login, plan to include a google auithenticator libary so one time password can be used,
 send email on config change or login
 send SMs via textlocal or nexmo, 
   may try and support tokenised URL 
   may try and support SSL URLs
 split config for I/O from web server, may leave it depends on code space
 add configurable MQTT WILL topic and messages, 
 SSL MQTT
 support for some I2C sensors, list TBC

add 
 MQTT broker, such a mosquitto on a PI or cloudmqtt.com 
 MQTT dashboard app such as https://play.google.com/store/apps/details?id=net.routix.mqttdash

and you have an internet of things  mobile remote control I/o board like this https://github.com/species5618/FSBrowserNG/blob/master/docs/deviceUPDashboard.png

add some node-red for some clever stuff

**Comment by Saaif88** [comment]
Hello species5618,

I just tried to use your fork of this project, but it does not work. I am getting a DHT error. I would post it as an issue on your fork, but I am not sure how.

Users/Saaif/Downloads/FSBrowserNG/FSBrowserNG.ino: In function 'void setup()':
FSBrowserNG:284: error: no matching function for call to 'DHT::begin(int)'
   dht.begin(DHT11);

/Users/Saaif/Downloads/FSBrowserNG/FSBrowserNG.ino:284:18: note: candidate is:
In file included from /Users/Saaif/Documents/Arduino/libraries/DHT_sensor_library/DHT_U.h:26:0,
                 from /Users/Saaif/Downloads/FSBrowserNG/FSBrowserNG.ino:4:
/Users/Saaif/Documents/Arduino/libraries/DHT_sensor_library/DHT.h:41:9: note: void DHT::begin()
    void begin(void);
         ^

I haven't changed any of the code, I have just installed all of the required libraries and this is the error I got.

**Comment by species5618** [comment]
Sorry my bad
I had to fork the dht library too

Simple change to allow me to set the dht type in setup() after declaration

https://github.com/species5618/DHT-sensor-library

its a simple mod, i will do a pull request for the original when i have time
