### ISSUE TITLE
Compile fails....

### ISSUE THREAD

**Issue by ddamron** [gmag11/FSBrowserNG#16]
I don't quite understand what this issue is.. I get this error:

C:\Users\SB 55\Documents\Arduino\libraries\ESPAsyncWebServer-master\src\WebHandlers.cpp:78:25: error: 'time' was not declared in this scope

   if(time(&last_modified) == 0) //time is not yet set

any ideas?

**Comment by species5618** [comment]
This us covered in the project notes

**Comment by species5618** [comment]
May be in the reader.MD

It's a known issue with different time libs
And requires and file to be created is I recall

**Comment by ddamron** [comment]
thanks.

**Comment by species5618** [comment]
move my project to https://github.com/species5618/MQTT_ESP8266 , please raise issue directly with me for any issus

**Comment by gmag11** [comment]
I guess, if you use 2.4.0 version of Arduino framework for ESP8266 you don't need to do anything.

Regards
