### ISSUE TITLE
ESP8266 not entering into AP mode

### ISSUE THREAD

**Issue by rolfz** [gmag11/FSBrowserNG#17]
Hello
I understand AP mode would be to generate his own SSID and password, the default parameters are inside the code. Unfortunately, my ESP runs into infinite loop (UART output sending constantly strange signs) when I bridge the digital input that should put the module into AP mode.

I would understand I can configure my module with my own router parameters once I am in AP mode with the module which is what I will do during the next step.

Could you please help me to understand what maybe wrong ?
To be mentioned that without putting the module in AP mode with the bridge, I get . (dots) on the UART port.
Kind regards Rolfz

**Comment by species5618** [comment]
Which code base
Gmag11 or mine

I have change the ap mode over ride pin to
Hold the i2c cl pin (based on wemos d1 pins) low

This was done to make it easier on my pcb

**Comment by rolfz** [comment]
I used gmag11/FSBrowserNG is there another FSBrowserNG code ? I will try with D1 as well.

**Comment by species5618** [comment]
Sorry ignore my comment
I have a version heavily customised.
Which a fellow use has been commenting here

**Comment by rolfz** [comment]
I used gmag11/FSBrowserNG is there another FSBrowserNG code ? I will try with D1 as well.
...
Ok, I tried with pin 16 which will be the one on my board. I also miss-interpreted the SSID code which is ESP+ChipID! and not just ESP. My copy works now with pin16 and no other changes.
