### ISSUE TITLE
How to enable DEBUG throughout

### ISSUE THREAD

**Issue by ddamron** [gmag11/FSBrowserNG#18]
Thank you for some wonderful programming!
I am actively playing with this code, trying to learn how it works..
I can't seem to figure out how to turn on DEBUG so I can see all the DBG_OUTPUT_PORT statements..
I have remarked out #define RELEASE, as per the comment..

I have also enabled debug with ALL in the arduino environment during compile time .. I'm getting debug from the ESP framework.. but not from FSBrowserNG..

Any help would be greatly appreciated as this would drastically speed up my learning..

Thanks again!

**Comment by ddamron** [comment]
Hello?  Anyone?

**Comment by moose4lord** [comment]
I commented out the "#define RELEASE" line in FSWebServerLib.h and get tons of debug info in the Serial Monitor. That seems to work for me. You could try changing one of the DEBUGLOG() statements to Serial.printf() and see if that shows up in the Serial Monitor.

**Comment by gmag11** [comment]
Exactly, the only thing you need is to comment out `#define RELEASE` on [header file](https://github.com/gmag11/FSBrowserNG/blob/master/src/FSWebServerLib.h#L24)

**Comment by ddamron** [comment]
Hrmm.. I did try that, but didn't seem to work.  I will reinstall and retry.  Thanks again!
Great work!

**Comment by ddamron** [comment]
Ok, fresh, clean install - and clean SPIFFS..

I also had issues with getting the device into AP mode - The documentation says if it doesn't find a config file it should automatically go into AP mode.  I did not find that was the case.

As well, to force the unit into AP mode, the docs state to tie pin 4 high.  That did not work for me, Through trial and error, I found that tying pin 4 LOW did indeed work.

Alas, commenting out #define RELEASE still did not enable debug..
I'm testing on a WEMOS D1 MINI board if that helps, 

I really hope it's something simple.. 
Can someone else confirm my findings?

**Comment by ddamron** [comment]
I got debug working!!
Here's where I messed up:

I didn't include both files as part of my project!  I just installed them as a library.. and that didn't work!

I then added both files (FSWebServerLib.cpp and .h) to my project, recompiled, and boom, it worked!

Thank you very much for your help!

I will close this now.
