### ISSUE TITLE
how to disable Authentication? (Logout)

### ISSUE THREAD

**Issue by ddamron** [gmag11/FSBrowserNG#20]
I can see where it uses MD5 hash to check authentication for HTTP Auth, Wifi AP mode, and OTA..

My question is, once a password has been entered correctly, how do I clear the credentials? 
ie: Logout support?

**Comment by gmag11** [comment]
You have to close browser.

**Comment by ddamron** [comment]
There must be a better way.. I've found sending a fake 401 works for some browsers..
Sending a response  with a custom header "WWW-Authenticate: Invalidate, Basic realm=logout" is also supposed to help..
My research into this topic has been mixed.. everyone suggests to close browser.. that's great.. but I want to add a logout button on my webpage.. and that seems tedious

**Comment by gmag11** [comment]
Sorry, I'm not a web developer. Probably there are better ways, like developing session handling with cookies, but I do not have enough time to investigate.

**Comment by gcassarino** [comment]
hello, happy to help! That can be done, please look at my project based on the wonderful work of Germán. On the administration page, a routine is implemented in JS to log out.
https://github.com/gcassarino/esp8266-Philips-RC6-tv-remote/blob/master/data/admin/admin.html#L60
