### ISSUE TITLE
Libraries versions

### ISSUE THREAD

**Issue by DanielJean007** [gmag11/FSBrowserNG#3]
Hi there,

First off, great job you've done here. Congrats.

I couldn't get this this project to work. I strongly believe that is because of libraries versions. I've had lots of problems with this sort of things in past projects of mine. Would it be possible for you to make available the libraries that you used in this project? I know that all the libs are available on GitHub, but to get all of them in the same version you build this project is gonna be a pain.

If you could do so, I'd really much appreciate it.

Thanks.

**Comment by gmag11** [comment]
Hi,

Could you send me any error log you are getting? What is the fault in? Compiler? 

Thanks

**Comment by DanielJean007** [comment]
When I upload the sketch my ESP prints out on the Serial Monitor the files in the SPIFFS. That's odd, right? So, although a fault doesn't show up, the system still doesn't work. U see?

**Comment by gmag11** [comment]
As `#define RELEASE` is commented on line 24 of .h file, debug info is printed to serial. If you send me that printout I can diagnose your compilation.

**Comment by gmag11** [comment]
@DanielJean007 Any update? May I close the issue?

**Comment by DanielJean007** [comment]
Yeah sure. Thanks. Sorry for not saying it earlier.
