### ISSUE TITLE
How to pick up additional setup data from HTML

### ISSUE THREAD

**Issue by bill-orange** [gmag11/FSBrowserNG#34]
To the config.html form in the UserConfig example I added to config.html a form line:

<input type="wukey" id="wukey" name="wukey" value="">

This is to pick up a Wunderground API key.  How to I pick this value up in the sketch?  I am confused on how your code works, I guess.

**Comment by species5618** [comment]
Config.html does not write to the user config 

Have a look at user2.html in the call back example
Which will store a user config by name 

Then in your main code, a line like this will fetch the value for you

String myValue ="";
ESPHTTPServer.load_user_config("myValueName", myValue);

**Comment by species5618** [comment]
Or look at
https://github.com/species5618/MQTT_Thermometer_ESP-01
Mqtt.html

**Comment by bill-orange** [comment]
I get it now. Worked like a charm.
