### ISSUE TITLE
Retrieve DST and time Zone into sketch

### ISSUE THREAD

**Issue by bill-orange** [gmag11/FSBrowserNG#35]
Is there a simple way to retrieve the Time Zone and DST flag into my sketch? I could use a user data field but then the user would be entering the same information twice,

**Comment by species5618** [comment]
the NTP client is global.
so its public methods are available

try 		Serial.print(NTP.getTimeZone());

**Comment by bill-orange** [comment]
Yup, works like a charm.  My sketch plots actual temp along with the Wunderground forecast.  using your excellent library, I can give one to a couple of friends without having to compile using their individual credentials and location info.
