### ISSUE TITLE
Conflict with new version of ESPAsyncWebServer

### ISSUE THREAD

**Issue by jirmed** [gmag11/FSBrowserNG#6]
Hello,

after installing Arduino IDE with all the libraries to a new PC I could not compile the demo application any more. I have discovered that the problem is in the latest version of ESPAsyncWebServer. I have dowloaded the bab5457 version of it  as of Jan 22, 2017 and after the hack with time.h the project compiles without errors.

Regards

Jiri

**Comment by gmag11** [comment]
I've had no problems when compiling with latest library versions. What error are you getting?

**Comment by gmag11** [comment]
Oh, wait! You are right. I have missed latest updates! Let me check what has happened.

**Comment by gmag11** [comment]
argument call type has changed to unsigned. I've updated calls so that it is forced to be unsigned. Check develop branch

**Comment by jirmed** [comment]
With the develop version it compiles OK.
