### ISSUE TITLE
Unable to edit index.html

### ISSUE THREAD

**Issue by SrikanthBala** [gmag11/FSBrowserNG#69]
I am using FS browser in my projects on ESP8266 for some time now. I am using ESP8266 at 160 Mhz with 2MB Code and 2MB SPIFFS
However I have a strange problem. I can edit all files but not files ending .html like index.html. They somehow seem to be locked.
I can delete the file however and recreate a file like index.html using the 'Create' option. Then I can copy and paste the code from my desktop editor and can save it with Ctrl S. I can edit it also as long as I am on the page. If I reboot or reload, I cannot access files with .html extensions but all other code like myjava.js remain editable. Right clicking on files with extension .html shows only the Download and Delete options, not the Edit option
I distinctly remember being able to edit html files earlier on other project
What is the possible problem ?

**Comment by SrikanthBala** [comment]
I realized that the previous time around I had name my file index.htm. If I do this the file can be loaded and edited. So I guess the javascript based editor ACE does not allow editing of .html files

**Comment by JeffersonRyan** [comment]
Maybe you are using an outdated version of the ACE Editor. Some old version has issues with any file with an extension with more than 3 letters. The editor that comes with the current FSBrowserNG examples does not have this issue.
