### ISSUE TITLE
How to add own sensor

### ISSUE THREAD

**Issue by jirmed** [gmag11/FSBrowserNG#7]
Hello Germán.

First of all - great library. Thank you for it.

I am a newbie to both C++ and Arduino so it gave me quite some time to understand how it works. Now I think I have a rough idea. I wanted to add my own sensors to the code. As I understood the JSON on URL /all returns the value of the analog input + all GPIOs. I wanted to add something slightly more complex like digital thermometer.

I tried to add following code into the setup():

`
    ESPHTTPServer.on("/temperature", HTTP_GET, [ESPHTTPServer](AsyncWebServerRequest *request) { 
      sensors.requestTemperatures();
      String json = "{\"temp\":"+String(sensors.getTempCByIndex(0))+"}";
      request->send(200, "text/json", json);
      json = String();       
    });
`

Unfortunately on compile I get following error:

`FSBrowserNG:35: error: 'AsyncWebServer' is not an accessible base of 'AsyncFSWebServer'`

After some googling I have found a solution by modifing FSWebServerLib.h line

`class AsyncFSWebServer : AsyncWebServer { `

to 

`class AsyncFSWebServer : public AsyncWebServer { `

That modification helped, the project compiles successfully and gives expected results.

My question is whether I can achieve the same without modifying the library.

Regards

Jiri

**Comment by gmag11** [comment]
Hi,

I had the same problem some time ago. I remember that change and I thought it should be there. Keep it so. I can add that change in next commit... or you can do a pull request if you like to.

My intention is to let people use my library as an extension to ESPAsyncWebServer, so that must be public.

Thank you!

**Comment by gmag11** [comment]
Fixed in https://github.com/gmag11/FSBrowserNG/commit/1b7c60f49912f3065ef8641c92b62417eab8e381

In develop branch by the moment

**Comment by gmag11** [comment]
I've updated master branch to include this change
