### ISSUE TITLE
call of overloaded 'arg(int)' is ambiguous

### ISSUE THREAD

**Issue by zargooshifar** [gmag11/FSBrowserNG#8]
i get this error: 
 :|

_Arduino: 1.8.1 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, 40MHz, QIO, 115200, 4M (3M SPIFFS), nodemcu, Disabled, None"

sketch\FSWebServerLib.cpp: In member function 'void AsyncFSWebServer::handleFileCreate(AsyncWebServerRequest*)':

FSWebServerLib.cpp:571: error: call of overloaded 'arg(int)' is ambiguous

     String path = request->arg(0);

                                 ^

sketch\FSWebServerLib.cpp:571:33: note: candidates are:

In file included from sketch\FSWebServerLib.h:17:0,

                 from sketch\FSWebServerLib.cpp:6:

..\Arduino\libraries\ESPAsyncWebServer-master\src/ESPAsyncWebServer.h:246:19: note: const String& AsyncWebServerRequest::arg(const String&) const

     const String& arg(const String& name) const; // get request argument value by name

                   ^

..\Arduino\libraries\ESPAsyncWebServer-master\src/ESPAsyncWebServer.h:247:19: note: const String& AsyncWebServerRequest::arg(const __FlashStringHelper*) const

     const String& arg(const __FlashStringHelper * data) const; // get request argument value by F(name)    

                   ^

..\Arduino\libraries\ESPAsyncWebServer-master\src/ESPAsyncWebServer.h:248:19: note: const String& AsyncWebServerRequest::arg(size_t) const

     const String& arg(size_t i) const;           // get request argument value by number

                   ^

sketch\FSWebServerLib.cpp: In member function 'void AsyncFSWebServer::handleFileDelete(AsyncWebServerRequest*)':

FSWebServerLib.cpp:590: error: call of overloaded 'arg(int)' is ambiguous

     String path = request->arg(0);

                                 ^

sketch\FSWebServerLib.cpp:590:33: note: candidates are:

In file included from sketch\FSWebServerLib.h:17:0,

                 from sketch\FSWebServerLib.cpp:6:

..\Arduino\libraries\ESPAsyncWebServer-master\src/ESPAsyncWebServer.h:246:19: note: const String& AsyncWebServerRequest::arg(const String&) const

     const String& arg(const String& name) const; // get request argument value by name

                   ^

..\Arduino\libraries\ESPAsyncWebServer-master\src/ESPAsyncWebServer.h:247:19: note: const String& AsyncWebServerRequest::arg(const __FlashStringHelper*) const

     const String& arg(const __FlashStringHelper * data) const; // get request argument value by F(name)    

                   ^

..\Arduino\libraries\ESPAsyncWebServer-master\src/ESPAsyncWebServer.h:248:19: note: const String& AsyncWebServerRequest::arg(size_t) const

     const String& arg(size_t i) const;           // get request argument value by number

                   ^

exit status 1
call of overloaded 'arg(int)' is ambiguous

**Comment by gmag11** [comment]
Hi, please test develop branch and tell me if it solves this problem

**Comment by zargooshifar** [comment]
working now, ty
